# Generated by Django 4.2.30 on 2026-04-12 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('action', 'Action')], max_length=10)),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('client_id', models.CharField(blank=True, help_text='Client-generated UUID for new records', max_length=64)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('applied', 'Applied'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('ignored_duplicate', 'Ignored Duplicate')], default='pending', max_length=24)),
                ('error_detail', models.TextField(blank=True)),
                ('cursor_before', models.CharField(blank=True, max_length=255)),
                ('cursor_after', models.CharField(blank=True, max_length=255)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.PositiveBigIntegerField(help_text='Client-side sequence number for ordering')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_queue',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='SyncCursor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('device_id', models.CharField(max_length=128)),
                ('stream_name', models.CharField(default='core', max_length=50)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_version', models.BigIntegerField(default=0)),
                ('cursor_token', models.CharField(blank=True, max_length=255)),
                ('entity_types', models.JSONField(blank=True, default=list, help_text='List of entity types tracked')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_cursors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_cursors',
            },
        ),
        migrations.CreateModel(
            name='DeviceOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('operation', models.CharField(max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('event_version', models.BigIntegerField(default=1)),
                ('outbox_state', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('acked', 'Acked'), ('dead_letter', 'Dead Letter')], db_index=True, default='pending', max_length=12)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_outbox', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_outbox',
            },
        ),
        migrations.CreateModel(
            name='ConflictLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=64)),
                ('server_version', models.JSONField(default=dict)),
                ('client_version', models.JSONField(default=dict)),
                ('resolution', models.CharField(choices=[('server_wins', 'Server Wins'), ('client_wins', 'Client Wins'), ('merged', 'Merged'), ('manual', 'Manual')], default='server_wins', max_length=15)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('sync_queue_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts', to='sync.syncqueue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_conflicts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_conflicts',
            },
        ),
        migrations.CreateModel(
            name='SyncSession',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sync.synccursor',),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['user', 'status', 'created_at_server'], name='sync_queue_user_id_d505d9_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['entity_type', 'entity_id'], name='sync_queue_entity__044a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['device_id', 'created_at_server'], name='sync_queue_device__423da8_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncqueue',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', None), _negated=True), fields=('device_id', 'idempotency_key'), name='sync_queue_device_idempotency_unique'),
        ),
        migrations.AddIndex(
            model_name='synccursor',
            index=models.Index(fields=['user', 'device_id'], name='sync_cursor_user_id_b76f1e_idx'),
        ),
        migrations.AddIndex(
            model_name='synccursor',
            index=models.Index(fields=['stream_name', 'last_sync_at'], name='sync_cursor_stream__87be7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='synccursor',
            unique_together={('device_id', 'stream_name')},
        ),
        migrations.AddIndex(
            model_name='deviceoutbox',
            index=models.Index(fields=['device_id', 'outbox_state', 'next_retry_at'], name='device_outb_device__961898_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceoutbox',
            index=models.Index(fields=['user', 'outbox_state'], name='device_outb_user_id_bb3d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceoutbox',
            index=models.Index(fields=['created_at_server'], name='device_outb_created_589293_idx'),
        ),
        migrations.AddConstraint(
            model_name='deviceoutbox',
            constraint=models.UniqueConstraint(fields=('device_id', 'entity_type', 'entity_id', 'event_version', 'operation'), name='device_outbox_event_unique'),
        ),
        migrations.AddIndex(
            model_name='conflictlog',
            index=models.Index(fields=['user', 'resolved_at'], name='sync_confli_user_id_c58546_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='sync_confli_entity__f899f6_idx'),
        ),
    ]
