# Generated by Django 4.2.30 on 2026-04-12 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('location_data', models.JSONField(blank=True, default=dict)),
                ('event_type', models.CharField(choices=[('internal', 'Internal'), ('public', 'Public'), ('service', 'Service'), ('custom', 'Custom')], default='internal', max_length=20)),
                ('scope', models.CharField(choices=[('organization', 'Organization'), ('group', 'Group'), ('public', 'Public'), ('private', 'Private')], default='organization', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('live', 'Live'), ('ended', 'Ended'), ('canceled', 'Canceled')], default='draft', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'org_events',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('group_type', models.CharField(choices=[('staff', 'Staff'), ('attendee', 'Attendee'), ('vip', 'VIP'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='organizations.event')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'org_groups',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('organization', 'Organization'), ('unit', 'Unit'), ('branch', 'Branch')], default='organization', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=16)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('description', models.TextField(blank=True)),
                ('locale', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('ur', 'Urdu')], default='en', max_length=5)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
                ('parent_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='organizations.organization')),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('group_leader', 'Group Leader'), ('staff', 'Staff'), ('general_user', 'General User')], db_index=True, default='general_user', max_length=24)),
                ('membership_status', models.CharField(choices=[('active', 'Active'), ('muted', 'Muted'), ('removed', 'Removed')], db_index=True, default='active', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'org_group_members',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='organizations.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('organization_admin', 'Organization Admin'), ('manager', 'Manager'), ('group_leader', 'Group Leader'), ('staff', 'Staff'), ('general_user', 'General User')], db_index=True, default='general_user', max_length=24)),
                ('membership_status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended'), ('left', 'Left')], db_index=True, default='active', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'org_members',
                'indexes': [models.Index(fields=['organization', 'role'], name='org_members_organiz_e32f89_idx'), models.Index(fields=['user', 'membership_status'], name='org_members_user_id_d6c7b2_idx'), models.Index(fields=['updated_at_server'], name='org_members_updated_cdab57_idx')],
                'unique_together': {('organization', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='organizatio_slug_5b8b37_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['owner', 'status'], name='organizatio_owner_i_fc7f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['parent_organization'], name='organizatio_parent__5490d0_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['updated_at_server'], name='organizatio_updated_999d8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(check=models.Q(('id', models.F('parent_organization')), _negated=True), name='org_parent_not_self'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group', 'role'], name='org_group_m_group_i_7a2916_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['user', 'membership_status'], name='org_group_m_user_id_43e83f_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['updated_at_server'], name='org_group_m_updated_9d93d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['organization', 'status'], name='org_groups_organiz_c92d40_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['event'], name='org_groups_event_i_59b94f_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['leader'], name='org_groups_leader__ef0856_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['updated_at_server'], name='org_groups_updated_2315a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'status'], name='org_events_organiz_9e8070_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by'], name='org_events_created_6ac5e8_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'scope'], name='org_events_event_t_8d53e0_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['starts_at'], name='org_events_starts__39baa9_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['updated_at_server'], name='org_events_updated_4a8bb3_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__isnull', True), ('starts_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='event_end_after_start'),
        ),
    ]
