# Generated by Django 4.2.30 on 2026-04-12 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('direct', 'Direct'), ('group', 'Group'), ('event', 'Event Channel'), ('organization', 'Organization Channel')], default='group', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='chat_avatars/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='organizations.event')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='organizations.group')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='organizations.organization')),
            ],
            options={
                'db_table': 'chat_rooms',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sender_device_id', models.CharField(blank=True, max_length=128)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image_placeholder', 'Image Placeholder'), ('voice_placeholder', 'Voice Placeholder'), ('image', 'Image'), ('file', 'File'), ('audio', 'Audio'), ('system', 'System')], default='text', max_length=24)),
                ('content', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_attachments/')),
                ('delivery_state', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('seen', 'Seen')], db_index=True, default='queued', max_length=12)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('client_id', models.CharField(blank=True, db_index=True, help_text='Client-generated idempotency ID for offline sync', max_length=64)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.chatmessage')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('seen', 'Seen')], max_length=12)),
                ('status_device_id', models.CharField(blank=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='chat.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_message_statuses',
                'indexes': [models.Index(fields=['user', 'status', 'updated_at'], name='chat_messag_user_id_37021d_idx'), models.Index(fields=['message', 'updated_at'], name='chat_messag_message_851211_idx')],
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChatRoomMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('admin', 'Admin')], db_index=True, default='member', max_length=16)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_room_members',
                'indexes': [models.Index(fields=['room', 'role'], name='chat_room_m_room_id_0eed85_idx'), models.Index(fields=['user', 'updated_at_server'], name='chat_room_m_user_id_1f3a91_idx')],
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['organization', 'status'], name='chat_rooms_organiz_ad12e7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['event'], name='chat_rooms_event_i_8749f7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['group'], name='chat_rooms_group_i_2fd6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['type', 'is_active'], name='chat_rooms_type_b67d97_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['updated_at_server'], name='chat_rooms_updated_8c368c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'sent_at'], name='chat_messag_room_id_ff0f42_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'sent_at'], name='chat_messag_sender__7deb94_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['delivery_state', 'sent_at'], name='chat_messag_deliver_981c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['client_id'], name='chat_messag_client__e1f3e0_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['updated_at_server'], name='chat_messag_updated_c0ae2a_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('client_id', ''), _negated=True), fields=('sender', 'client_id'), name='chat_message_sender_client_id_unique'),
        ),
    ]
