# Generated by Django 4.2.30 on 2026-04-13 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr_engine', '0004_interactionrecord_interactionauditlog_and_more'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='qr_engine.interactionrecord'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='type',
            field=models.CharField(choices=[('direct', 'Direct'), ('group', 'Group'), ('interaction', 'Interaction'), ('event', 'Event Channel'), ('organization', 'Organization Channel')], default='group', max_length=20),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['interaction'], name='chat_rooms_interac_ea5e35_idx'),
        ),
    ]
