# Generated by Django 4.2.30 on 2026-04-12 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qr_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('queue_type', models.CharField(choices=[('standard', 'Standard'), ('priority', 'Priority'), ('hybrid', 'Hybrid')], default='standard', max_length=16)),
                ('max_capacity', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('current_serving', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paused', 'Paused'), ('closed', 'Closed')], db_index=True, default='open', max_length=10)),
                ('allow_rejoin', models.BooleanField(default=False)),
                ('is_token_based', models.BooleanField(default=True)),
                ('estimated_wait_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues', to='organizations.event')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues', to='organizations.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='organizations.organization')),
            ],
            options={
                'db_table': 'queues',
            },
        ),
        migrations.CreateModel(
            name='QueueSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], db_index=True, default='active', max_length=12)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('current_token_number', models.PositiveIntegerField(default=0)),
                ('last_called_token_number', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_queue_sessions', to=settings.AUTH_USER_MODEL)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='queue_control.queue')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_queue_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'queue_sessions',
            },
        ),
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=128)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('waiting', 'Waiting'), ('called', 'Called'), ('recalled', 'Recalled'), ('completed', 'Completed'), ('serving', 'Serving'), ('done', 'Done'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], db_index=True, default='issued', max_length=12)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('desk_number', models.PositiveIntegerField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('recalled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_wait_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('issued_from_scan_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_tickets', to='qr_engine.scantoken')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='queue_control.queue')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='queue_control.queuesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'queue_tickets',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='QueueActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_device_id', models.CharField(blank=True, max_length=128)),
                ('action', models.CharField(choices=[('next', 'Next'), ('call', 'Call'), ('skip', 'Skip'), ('recall', 'Recall'), ('complete', 'Complete'), ('cancel', 'Cancel'), ('session_open', 'Session Open'), ('session_close', 'Session Close')], db_index=True, max_length=20)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_actions', to=settings.AUTH_USER_MODEL)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='queue_control.queue')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='queue_control.queuesession')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='queue_control.queueticket')),
            ],
            options={
                'db_table': 'queue_action_logs',
            },
        ),
        migrations.AddIndex(
            model_name='queueticket',
            index=models.Index(fields=['queue', 'status', 'number'], name='queue_ticke_queue_i_7bfaaf_idx'),
        ),
        migrations.AddIndex(
            model_name='queueticket',
            index=models.Index(fields=['session', 'status', 'number'], name='queue_ticke_session_878953_idx'),
        ),
        migrations.AddIndex(
            model_name='queueticket',
            index=models.Index(fields=['user', 'status'], name='queue_ticke_user_id_270dea_idx'),
        ),
        migrations.AddIndex(
            model_name='queueticket',
            index=models.Index(fields=['issued_at'], name='queue_ticke_issued__36098a_idx'),
        ),
        migrations.AddIndex(
            model_name='queueticket',
            index=models.Index(fields=['updated_at_server'], name='queue_ticke_updated_bbee8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='queueticket',
            constraint=models.CheckConstraint(check=models.Q(('number__gte', 1)), name='queue_ticket_number_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='queueticket',
            constraint=models.CheckConstraint(check=models.Q(('priority__gte', 0)), name='queue_ticket_priority_gte_0'),
        ),
        migrations.AlterUniqueTogether(
            name='queueticket',
            unique_together={('session', 'number')},
        ),
        migrations.AddIndex(
            model_name='queuesession',
            index=models.Index(fields=['queue', 'status'], name='queue_sessi_queue_i_1fc785_idx'),
        ),
        migrations.AddIndex(
            model_name='queuesession',
            index=models.Index(fields=['started_at'], name='queue_sessi_started_067121_idx'),
        ),
        migrations.AddIndex(
            model_name='queuesession',
            index=models.Index(fields=['updated_at_server'], name='queue_sessi_updated_125bfa_idx'),
        ),
        migrations.AddConstraint(
            model_name='queuesession',
            constraint=models.CheckConstraint(check=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='queue_session_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='queuesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('queue',), name='unique_active_session_per_queue'),
        ),
        migrations.AddIndex(
            model_name='queueactionlog',
            index=models.Index(fields=['queue', 'created_at_server'], name='queue_actio_queue_i_43f5d1_idx'),
        ),
        migrations.AddIndex(
            model_name='queueactionlog',
            index=models.Index(fields=['session', 'created_at_server'], name='queue_actio_session_090da6_idx'),
        ),
        migrations.AddIndex(
            model_name='queueactionlog',
            index=models.Index(fields=['ticket', 'created_at_server'], name='queue_actio_ticket__8f5359_idx'),
        ),
        migrations.AddIndex(
            model_name='queueactionlog',
            index=models.Index(fields=['actor_user', 'created_at_server'], name='queue_actio_actor_u_4d3149_idx'),
        ),
        migrations.AddIndex(
            model_name='queueactionlog',
            index=models.Index(fields=['action', 'created_at_server'], name='queue_actio_action_e22faf_idx'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['organization', 'status'], name='queues_organiz_9810ab_idx'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['event'], name='queues_event_i_9e031e_idx'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['group'], name='queues_group_i_f245b9_idx'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['updated_at_server'], name='queues_updated_ed904e_idx'),
        ),
        migrations.AddConstraint(
            model_name='queue',
            constraint=models.CheckConstraint(check=models.Q(('max_capacity__gte', 0)), name='queue_max_capacity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='queue',
            constraint=models.CheckConstraint(check=models.Q(('current_serving__gte', 0)), name='queue_current_serving_gte_0'),
        ),
    ]
