# Generated by Django 4.2.30 on 2026-04-12 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('staff_only', 'Staff Only')], default='public', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_channels', to='organizations.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_channels', to='organizations.organization')),
            ],
            options={
                'db_table': 'broadcast_channels',
            },
        ),
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Info'), ('alert', 'Alert'), ('call_number', 'Call Number'), ('custom', 'Custom')], default='info', max_length=20)),
                ('target_mode', models.CharField(choices=[('group', 'Group'), ('organization_members', 'Organization Members'), ('selected_members', 'Selected Members')], default='organization_members', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='queued', max_length=12)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='broadcast.broadcastchannel')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broadcast_messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('seen', 'Seen'), ('failed', 'Failed')], db_index=True, default='queued', max_length=12)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='broadcast.broadcastmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broadcast_deliveries',
            },
        ),
        migrations.CreateModel(
            name='BroadcastSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='broadcast.broadcastchannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broadcast_subscriptions',
                'indexes': [models.Index(fields=['channel', 'is_muted'], name='broadcast_s_channel_0743d4_idx'), models.Index(fields=['user', 'updated_at_server'], name='broadcast_s_user_id_8a6613_idx')],
                'unique_together': {('channel', 'user')},
            },
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='broadcast.broadcastmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broadcast_recipients',
                'indexes': [models.Index(fields=['message'], name='broadcast_r_message_013a45_idx'), models.Index(fields=['user'], name='broadcast_r_user_id_e9faa5_idx'), models.Index(fields=['updated_at_server'], name='broadcast_r_updated_a2ae21_idx')],
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['channel', 'sent_at'], name='broadcast_m_channel_94b024_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['target_mode', 'status'], name='broadcast_m_target__944a10_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['scheduled_at'], name='broadcast_m_schedul_847619_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['updated_at_server'], name='broadcast_m_updated_9b98ef_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastdelivery',
            index=models.Index(fields=['user', 'status'], name='broadcast_d_user_id_8ce588_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastdelivery',
            index=models.Index(fields=['message', 'status'], name='broadcast_d_message_08c848_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastdelivery',
            index=models.Index(fields=['device_id'], name='broadcast_d_device__b5b87c_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastdelivery',
            index=models.Index(fields=['updated_at_server'], name='broadcast_d_updated_3822dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='broadcastdelivery',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='broadcastchannel',
            index=models.Index(fields=['organization', 'is_active'], name='broadcast_c_organiz_f68085_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastchannel',
            index=models.Index(fields=['group'], name='broadcast_c_group_i_9665fa_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastchannel',
            index=models.Index(fields=['updated_at_server'], name='broadcast_c_updated_6f0992_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='broadcastchannel',
            unique_together={('organization', 'name')},
        ),
    ]
