# Generated by Django 4.2.30 on 2026-04-13 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr_engine', '0004_interactionrecord_interactionauditlog_and_more'),
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastchannel',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_channels', to='qr_engine.interactionrecord'),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_messages', to='qr_engine.interactionrecord'),
        ),
        migrations.AddIndex(
            model_name='broadcastchannel',
            index=models.Index(fields=['interaction'], name='broadcast_c_interac_2e7f84_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['interaction', 'sent_at'], name='broadcast_m_interac_cfb668_idx'),
        ),
    ]
