// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcx2Ri2G9ofqXl_yUHoyvZKzL9zRUB4XQ',
    appId: '1:426320258517:web:5921ade43ac89d63a3895c',
    messagingSenderId: '426320258517',
    projectId: 'door-22ef3',
    authDomain: 'door-22ef3.firebaseapp.com',
    storageBucket: 'door-22ef3.firebasestorage.app',
    measurementId: 'G-QX4LSB6Z4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL9v45GGDwD7xPhVZLabFb5vD2vtefe8c',
    appId: '1:426320258517:android:56d6d5b4dfc66741a3895c',
    messagingSenderId: '426320258517',
    projectId: 'door-22ef3',
    storageBucket: 'door-22ef3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATuBpa2BaBSOelrlBFCudwzsqt8RvLMRo',
    appId: '1:426320258517:ios:2a87f5b40e4fbf52a3895c',
    messagingSenderId: '426320258517',
    projectId: 'door-22ef3',
    storageBucket: 'door-22ef3.firebasestorage.app',
    iosClientId: '426320258517-5if7b36dp5h9ghnfm76m602fn4qgeqre.apps.googleusercontent.com',
    iosBundleId: 'com.example.doorMobile',
  );
}
