# Generated by Django 4.2.30 on 2026-04-12 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queue_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
        ('qr_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantoken',
            name='queue_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_tokens', to='queue_control.queueticket'),
        ),
        migrations.AddField(
            model_name='scantoken',
            name='redeemed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_scan_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scantoken',
            name='scan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_obj', to='qr_engine.qrscan'),
        ),
        migrations.AddField(
            model_name='qrscan',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='qr_engine.qrcode'),
        ),
        migrations.AddField(
            model_name='qrscan',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrownermember',
            name='member_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_owner_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrownermember',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_qr_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrownermember',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_members', to='qr_engine.qrcode'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='organizations.event'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='organizations.group'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='queue_control.queue'),
        ),
        migrations.AddField(
            model_name='qralertrecipient',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='qr_engine.qralert'),
        ),
        migrations.AddField(
            model_name='qralertrecipient',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_deliveries', to='qr_engine.qrownermember'),
        ),
        migrations.AddField(
            model_name='qralert',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='qr_engine.qrcode'),
        ),
        migrations.AddField(
            model_name='qralert',
            name='responded_by_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to='qr_engine.qrownermember'),
        ),
        migrations.AddField(
            model_name='qralert',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='qr_engine.qrscan'),
        ),
        migrations.AddField(
            model_name='qralert',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_qr_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='scantoken',
            index=models.Index(fields=['status', 'expires_at'], name='qr_scan_tok_status_bcdcf6_idx'),
        ),
        migrations.AddIndex(
            model_name='scantoken',
            index=models.Index(fields=['scan'], name='qr_scan_tok_scan_id_fc6a21_idx'),
        ),
        migrations.AddIndex(
            model_name='scantoken',
            index=models.Index(fields=['updated_at_server'], name='qr_scan_tok_updated_bf8064_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscan',
            index=models.Index(fields=['qr_code', 'scanned_at'], name='qr_scans_qr_code_20f19d_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscan',
            index=models.Index(fields=['scanned_by', 'scanned_at'], name='qr_scans_scanned_edc4fb_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscan',
            index=models.Index(fields=['device_id', 'scanned_at'], name='qr_scans_device__971a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscan',
            index=models.Index(fields=['entity_type', 'mode'], name='qr_scans_entity__e76620_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscan',
            index=models.Index(fields=['updated_at_server'], name='qr_scans_updated_92eff4_idx'),
        ),
        migrations.AddIndex(
            model_name='qrownermember',
            index=models.Index(fields=['qr_code', 'is_active', 'priority'], name='qr_owner_me_qr_code_58ad15_idx'),
        ),
        migrations.AddIndex(
            model_name='qrownermember',
            index=models.Index(fields=['owner', 'member_type'], name='qr_owner_me_owner_i_fe1cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='qrownermember',
            index=models.Index(fields=['notify_role', 'availability'], name='qr_owner_me_notify__bbc137_idx'),
        ),
        migrations.AddIndex(
            model_name='qrownermember',
            index=models.Index(fields=['updated_at_server'], name='qr_owner_me_updated_015718_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['organization', 'status'], name='qr_codes_organiz_0d5a56_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['event'], name='qr_codes_event_i_42e0c5_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['group'], name='qr_codes_group_i_a49794_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['queue'], name='qr_codes_queue_i_9959da_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['entity_type', 'mode', 'is_active'], name='qr_codes_entity__d81bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['expires_at'], name='qr_codes_expires_a30ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['updated_at_server'], name='qr_codes_updated_15ae5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='qrcode',
            constraint=models.CheckConstraint(check=models.Q(('scans_limit__gte', 0)), name='qr_scans_limit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='qrcode',
            constraint=models.CheckConstraint(check=models.Q(('scans_count__gte', 0)), name='qr_scans_count_gte_0'),
        ),
        migrations.AddIndex(
            model_name='qralertrecipient',
            index=models.Index(fields=['alert', 'notify_role'], name='qr_alert_re_alert_i_425dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='qralertrecipient',
            index=models.Index(fields=['member', 'response_status'], name='qr_alert_re_member__75d012_idx'),
        ),
        migrations.AddIndex(
            model_name='qralertrecipient',
            index=models.Index(fields=['updated_at_server'], name='qr_alert_re_updated_a96296_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qralertrecipient',
            unique_together={('alert', 'member')},
        ),
        migrations.AddIndex(
            model_name='qralert',
            index=models.Index(fields=['qr_code', 'status', 'created_at_server'], name='qr_alerts_qr_code_7db6ee_idx'),
        ),
        migrations.AddIndex(
            model_name='qralert',
            index=models.Index(fields=['scan'], name='qr_alerts_scan_id_d0075e_idx'),
        ),
        migrations.AddIndex(
            model_name='qralert',
            index=models.Index(fields=['updated_at_server'], name='qr_alerts_updated_b767f2_idx'),
        ),
    ]
