# Generated by Django 4.2.30 on 2026-04-13 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qr_engine', '0003_dynamic_template_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='open', max_length=20)),
                ('current_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_records', to='qr_engine.templateworkflowstate')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_interactions', to=settings.AUTH_USER_MODEL)),
                ('qr_entity', models.ForeignKey(db_column='qr_entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='interaction_records', to='qr_engine.qrcode')),
                ('scan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_record', to='qr_engine.qrscan')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interaction_records', to='qr_engine.interactiontemplate')),
            ],
            options={
                'db_table': 'qr_interaction_records',
            },
        ),
        migrations.CreateModel(
            name='InteractionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('snapshot_json', models.JSONField(blank=True, default=dict)),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('from_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_from', to='qr_engine.templateworkflowstate')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='qr_engine.interactionrecord')),
                ('to_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_to', to='qr_engine.templateworkflowstate')),
            ],
            options={
                'db_table': 'qr_interaction_audit_logs',
                'ordering': ['created_at_server'],
            },
        ),
        migrations.AddIndex(
            model_name='interactionrecord',
            index=models.Index(fields=['template', 'status'], name='qr_interact_templat_0e7e41_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionrecord',
            index=models.Index(fields=['qr_entity', 'initiated_at'], name='qr_interact_qr_enti_6fd4b0_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionrecord',
            index=models.Index(fields=['initiated_by', 'initiated_at'], name='qr_interact_initiat_9277a5_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionrecord',
            index=models.Index(fields=['current_state'], name='qr_interact_current_0d9f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionrecord',
            index=models.Index(fields=['updated_at_server'], name='qr_interact_updated_8ed073_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionauditlog',
            index=models.Index(fields=['interaction', 'created_at_server'], name='qr_interact_interac_47557b_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionauditlog',
            index=models.Index(fields=['actor', 'created_at_server'], name='qr_interact_actor_i_7db9e1_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionauditlog',
            index=models.Index(fields=['action', 'created_at_server'], name='qr_interact_action_d958f9_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionauditlog',
            index=models.Index(fields=['updated_at_server'], name='qr_interact_updated_6ade25_idx'),
        ),
    ]
