# Generated by Django 4.2.30 on 2026-04-15 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr_engine', '0004_interactionrecord_interactionauditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('booked', 'Booked'), ('booked_till', 'Booked Till'), ('meeting_live', 'Meeting Live')], db_index=True, default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='booked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='door_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='join_code',
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='parent_qr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_qrs', to='qr_engine.qrcode'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='text_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='entity_type',
            field=models.CharField(choices=[('organization', 'Organization'), ('event', 'Event'), ('group', 'Group'), ('queue', 'Queue'), ('door', 'Door')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='mode',
            field=models.CharField(choices=[('check_in', 'Check-In'), ('queue_join', 'Queue Join'), ('open_chat', 'Open Chat'), ('subscribe_broadcast', 'Subscribe Broadcast'), ('custom_action', 'Custom Action'), ('visitor_log', 'Visitor Log'), ('trip_log', 'Trip Log'), ('gather_mode', 'Gather Mode')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='payload_type',
            field=models.CharField(choices=[('check_in', 'Check-In'), ('queue_join', 'Queue Join'), ('open_chat', 'Open Chat'), ('subscribe_broadcast', 'Subscribe Broadcast'), ('custom_action', 'Custom Action'), ('visitor_log', 'Visitor Log'), ('trip_log', 'Trip Log'), ('gather_mode', 'Gather Mode')], default='custom_action', max_length=30),
        ),
        migrations.AlterField(
            model_name='qrscan',
            name='entity_type',
            field=models.CharField(choices=[('organization', 'Organization'), ('event', 'Event'), ('group', 'Group'), ('queue', 'Queue'), ('door', 'Door')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='qrscan',
            name='mode',
            field=models.CharField(choices=[('check_in', 'Check-In'), ('queue_join', 'Queue Join'), ('open_chat', 'Open Chat'), ('subscribe_broadcast', 'Subscribe Broadcast'), ('custom_action', 'Custom Action'), ('visitor_log', 'Visitor Log'), ('trip_log', 'Trip Log'), ('gather_mode', 'Gather Mode')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['parent_qr', 'availability_status'], name='qr_codes_parent__352fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['join_code'], name='qr_codes_join_co_bc1f76_idx'),
        ),
    ]
