# Generated by Django 4.2.30 on 2026-04-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_engine', '0005_qrcode_availability_status_qrcode_available_from_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='qrcode',
            name='qr_codes_parent__352fc9_idx',
        ),
        migrations.RemoveIndex(
            model_name='qrcode',
            name='qr_codes_join_co_bc1f76_idx',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='available_until',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='booked_until',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='door_profile',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='join_code',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='parent_qr',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='text_options',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='entity_type',
            field=models.CharField(choices=[('organization', 'Organization'), ('event', 'Event'), ('group', 'Group'), ('queue', 'Queue')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='mode',
            field=models.CharField(choices=[('check_in', 'Check-In'), ('queue_join', 'Queue Join'), ('open_chat', 'Open Chat'), ('subscribe_broadcast', 'Subscribe Broadcast'), ('custom_action', 'Custom Action')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='payload_type',
            field=models.CharField(choices=[('check_in', 'Check-In'), ('queue_join', 'Queue Join'), ('open_chat', 'Open Chat'), ('subscribe_broadcast', 'Subscribe Broadcast'), ('custom_action', 'Custom Action')], default='custom_action', max_length=30),
        ),
        migrations.AlterField(
            model_name='qrscan',
            name='entity_type',
            field=models.CharField(choices=[('organization', 'Organization'), ('event', 'Event'), ('group', 'Group'), ('queue', 'Queue')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='qrscan',
            name='mode',
            field=models.CharField(choices=[('check_in', 'Check-In'), ('queue_join', 'Queue Join'), ('open_chat', 'Open Chat'), ('subscribe_broadcast', 'Subscribe Broadcast'), ('custom_action', 'Custom Action')], db_index=True, max_length=30),
        ),
    ]
