# Generated by Django 4.2.30 on 2026-04-12 19:37

import apps.auth_identity.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=apps.auth_identity.models._generate_public_id, max_length=32, unique=True)),
                ('anonymous_id', models.CharField(default=apps.auth_identity.models._generate_anonymous_id, max_length=40, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('owner', 'Owner'), ('organization_admin', 'Organization Admin'), ('manager', 'Manager'), ('group_leader', 'Group Leader'), ('staff', 'Staff'), ('general_user', 'General User')], default='general_user', max_length=24)),
                ('locale', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('ur', 'Urdu')], default='en', max_length=5)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'db_table': 'auth_users',
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('fcm_token', models.TextField(blank=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=10)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('os_version', models.CharField(blank=True, max_length=64)),
                ('public_key', models.TextField(blank=True)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at_client', models.DateTimeField(blank=True, null=True)),
                ('updated_at_client', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True, db_index=True)),
                ('sync_status', models.CharField(choices=[('pending_local', 'Pending Local'), ('queued_sync', 'Queued Sync'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='synced', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_by_device_id', models.CharField(blank=True, max_length=128)),
                ('last_modified_by_device_id', models.CharField(blank=True, max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_devices',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('refresh_jti', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=12)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='auth_identity.userdevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_sessions',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=8)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='sms', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=12)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(db_index=True, default=False)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_user_agent', models.TextField(blank=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auth_otps',
                'indexes': [models.Index(fields=['phone', 'used'], name='auth_otps_phone_cc8730_idx'), models.Index(fields=['phone', 'status', 'created_at_server'], name='auth_otps_phone_0575e7_idx'), models.Index(fields=['expires_at'], name='auth_otps_expires_5da7f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_email_verifications',
            },
        ),
    ]
