# Generated by Django 4.2.30 on 2026-04-12 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
        ('auth_identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'status'], name='auth_user_s_user_id_ac0cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='auth_user_s_expires_3df8ae_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['issued_at'], name='auth_user_s_issued__25bd55_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'is_active'], name='auth_user_d_user_id_2bc9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['fcm_token'], name='auth_user_d_fcm_tok_f633b8_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['updated_at_server'], name='auth_user_d_updated_ffc163_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdevice',
            unique_together={('user', 'device_id')},
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['user', 'status'], name='auth_email__user_id_78d7d4_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['email', 'status'], name='auth_email__email_e4e36b_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['expires_at'], name='auth_email__expires_e35532_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='auth_users_phone_6fce18_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['public_id'], name='auth_users_public__c50b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['anonymous_id'], name='auth_users_anonymo_fb7f69_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='auth_users_role_1dc74c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['updated_at_server'], name='auth_users_updated_99c49a_idx'),
        ),
    ]
