# Generated by ChatGPT for Phase 1 identity cleanup.

from django.db import migrations, models


def backfill_identity_fields(apps, schema_editor):
    User = apps.get_model("auth_identity", "User")
    for user in User.objects.all().iterator():
        updates = []

        if not user.email:
            user.email = f"{user.public_id}@placeholder.door.local"
            updates.append("email")
        else:
            normalized_email = user.email.strip().lower()
            if normalized_email != user.email:
                user.email = normalized_email
                updates.append("email")

        phone_value = getattr(user, "phone_number", None) or getattr(user, "phone", "")
        if phone_value:
            normalized_phone = phone_value.strip()
            if normalized_phone != phone_value:
                user.phone_number = normalized_phone
                updates.append("phone_number")

        if not user.full_name:
            user.full_name = user.email.split("@", 1)[0].replace(".", " ").strip() or user.public_id
            updates.append("full_name")

        if not getattr(user, "status", None):
            user.status = "active"
            updates.append("status")

        if updates:
            user.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ("auth_identity", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending_verification", "Pending Verification"),
                    ("suspended", "Suspended"),
                    ("disabled", "Disabled"),
                ],
                db_index=True,
                default="active",
                max_length=24,
            ),
        ),
        migrations.RunPython(backfill_identity_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(db_column="phone", max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="auth_users_email_617476_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["status", "is_active"], name="auth_users_status_7a9ef4_idx"),
        ),
    ]
