# Generated by Django 4.2.30 on 2026-04-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_identity', '0004_remove_user_auth_users_phone_6fce18_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.CharField(blank=True, help_text='Short bio/intro line shown on profile.', max_length=240),
        ),
    ]
